# Generated by Django 5.1.3 on 2025-06-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0004_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='webinar_images/'),
        ),
    ]
