# Generated by Django 5.1.3 on 2025-06-03 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0005_webinar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='live_stream_link',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='price',
        ),
        migrations.AddField(
            model_name='webinar',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('marketing', 'Marketing'), ('business', 'Business'), ('design', 'Design'), ('health', 'Health')], default='tech', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinar',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinar',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='speaker_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='speaker_name',
            field=models.CharField(default='Reetu Malhotra', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinar',
            name='time',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webinar',
            name='date',
            field=models.DateField(),
        ),
    ]
