# Generated by Django 5.1.3 on 2025-06-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0006_remove_webinar_live_stream_link_remove_webinar_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
