# Generated by Django 5.1.3 on 2025-06-04 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0009_alter_booking_unique_together_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'webinar')},
        ),
    ]
