# Generated by Django 5.1.3 on 2025-06-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0012_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='registration_link',
            new_name='meet_link',
        ),
    ]
